### ISSUE TITLE
Does not handle arrays of React Elements

### ISSUE THREAD

**Issue by johnnyreilly** [rogeriochaves/jasmine-react-diff#2]
Hey!

I love what you've done here - I heard about it from @vvo [here](https://github.com/facebook/react/issues/4835#issuecomment-148708582).  The one thing that tripped me up was that it doesn't handle arrays of React Elements - it only accepts single React Elements.  

I think this could be handled by going from this:

```
const formatReactComponents = (defaultFormatter) => (value) =>
  isReact(value) ? `\n${reactFormatter(value)}\n` : defaultFormatter(value);
```

To this:

```
const formatReactComponents = (defaultFormatter) => (value) =>
  (isReact(value) || (Array.isArray(value) && value.every(isReact))) ? `\n${reactFormatter(value)}\n` : defaultFormatter(value);
```

What do you think?  Happy to submit PR.  Or alternatively emphasing in the docs that this doesn't cater for arrays of React Elements.

**Comment by vvo** [comment]
@johnnyreilly One could just reuse https://github.com/algolia/react-element-to-jsx-string instead of https://github.com/rogeriochaves/react-decompiler. We handle more cases I believe

**Comment by rogeriochaves** [comment]
Thanks for the suggestions! I've implemented something similiar, but instead of `.every` I actually used `.some`, so you can mix up react and normal values and still have everything nicely formatted.

Thanks again, and I'd be glad to get some PRs for any changes you might want to add in the future :)

#### Update

Also now it's formatting react elements inside javascript objects

**Comment by johnnyreilly** [comment]
Great!
